import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const notoSansKr = Noto_Sans_KR({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansKr.className}>
        <ul className="p-4">
          <Link
            href="/"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            홈
          </Link>
          <Link
            href="/game1"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            컬러 플리퍼
          </Link>
          <Link
            href="/game2"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            카운터
          </Link>
          <Link
            href="/game3"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            리뷰 캐러셀
          </Link>
        </ul>
        {children}
      </body>
    </html>
  );
}
