import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { NextUIProvider } from "@nextui-org/react";

const notoSansKr = Noto_Sans_KR({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={notoSansKr.className}>
        <ul className="p-4">
          <Link
            href="/"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            홈
          </Link>
          <Link
            href="/game1"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            컬러 플리퍼
          </Link>
          <Link
            href="/game2"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            카운터
          </Link>
          <Link
            href="/game3"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            리뷰 캐러셀
          </Link>
          <Link
            href="/game4"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            반응형 네비게이션
          </Link>
          <Link
            href="/game5"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            사이드바
          </Link>
          <Link
            href="/game6"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            모달
          </Link>
          <Link
            href="/game7"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            FAQ
          </Link>
          <Link
            href="/game8"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            식당 메뉴판
          </Link>
          <Link
            href="/game9"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            비디오 배경
          </Link>
          <Link
            href="/game10"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            스크롤
          </Link>
          <Link
            href="/game11"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            서로다른 내용
          </Link>
          <Link
            href="/game12"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            카운트다운 시계
          </Link>
          <Link
            href="/game13"
            className="border-black hover:bg-gray-100 p-1 rounded-md"
          >
            로렘입숨 만들기
          </Link>
        </ul>
        {children}
      </body>
    </html>
  );
}
